# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.4.0
      with:
        java-version: 21
        distribution: oracle

    - name: Set up Maven
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        tar -xvf apache-maven-3.9.9-bin.tar.gz
        mv apache-maven-3.9.9 /opt/
        echo "/opt/apache-maven-3.9.9/bin" >> $GITHUB_PATH

    - name: Build with Maven
      working-directory: ./java/testng
      run: |
        mvn clean compile -q

    - name: Docker Compose with Tests Action
      uses: adambirds/docker-compose-action@v1.5.0
      with:
        compose-file: java/testng/healenium/docker-compose.yaml
      continue-on-error: false

    - name: Docker status
      working-directory: ./java/testng
      run: |
        docker ps -a

    # Chrome
    - name: Test with Maven Chrome
      working-directory: ./java/testng
      run: |
        mvn clean test -DDriverType=Chrome
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      with:
        name: Chrome-SelfHealingTestReport
        path: ./java/testng/target/surefire-reports

    # Healenium
    - name: Test with Maven Chrome Healenium
      working-directory: ./java/testng
      run: |
        mvn clean test -DDriverType=ChromeHealenium
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      with:
        name: Healenium-SelfHealingTestReport
        path: ./java/testng/target/surefire-reports
  
    # TestRigor
    - name: Test with Maven Chrome TestRigor
      working-directory: ./java/testng
      run: |
        mvn clean test -DDriverType=ChromeTestRigor
      continue-on-error: true
  
    - uses: actions/upload-artifact@v4
      with:
        name: TestRigor-SelfHealingTestReport
        path: ./java/testng/target/surefire-reports
