# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker

    steps:
    - uses: actions/checkout@v4

    - name: Set up Maven
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        tar -xvf apache-maven-3.9.9-bin.tar.gz
        mv apache-maven-3.9.9 /opt/
        echo "/opt/apache-maven-3.9.9/bin" >> $GITHUB_PATH
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up system variables
      run: |
        echo $JAVA_HOME >> $GITHUB_PATH
        java --version

    - name: Build with Maven
      working-directory: ./java/testng
      run: mvn compile

    - name: Raise Healenium docker servers
      working-directory: ./java/testng/healenium
      run:  docker-compose up -d

    - name: Test with Maven
      working-directory: ./java/testng
      run: mvn test

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./java/testng/target/surefire-reports

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
